/**
 * Menu synced from Takeaway.com — Monastery Tavern | Механа Манастира (EUR).
 */

export type MenuCategory =
  | "salads"
  | "mezze"
  | "appetizers"
  | "risotto"
  | "chicken"
  | "pork"
  | "beefLamb"
  | "seafood"
  | "desserts"
  | "pizza"
  | "flatbread"
  | "softDrinks"
  | "hotDrinks"
  | "beer";

export interface MenuItem {
  id: string;
  name: string;
  nameBG: string;
  weight: string;
  price: number;
  category: MenuCategory;
  description: string;
  ingredients: string[];
  allergens?: string[];
  isPopular?: boolean;
}

export const MENU_CATEGORY_ORDER: MenuCategory[] = [
  "salads",
  "mezze",
  "appetizers",
  "risotto",
  "chicken",
  "pork",
  "beefLamb",
  "seafood",
  "desserts",
  "pizza",
  "flatbread",
  "softDrinks",
  "hotDrinks",
  "beer",
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "shopska-salad",
    name: "Shopska salad",
    nameBG: "Шопска салата",
    weight: "350 g",
    price: 7.45,
    category: "salads",
    description:
      "Tomatoes, cucumbers, peppers, onion, sirene and olive oil — the quiet Bulgarian classic.",
    ingredients: ["Tomatoes", "Cucumbers", "Peppers", "Onion", "Sirene", "Oil"],
    allergens: ["Milk"],
    isPopular: true,
  },
  {
    id: "ovcharska-bacon-chips",
    name: "Ovcharska salad with bacon chips",
    nameBG: "Овчарска салата с чипс от бекон",
    weight: "380 g",
    price: 9.21,
    category: "salads",
    description: "Village salad composition finished with crisp bacon chips.",
    ingredients: ["Garden vegetables", "Sirene", "Bacon chips", "Dressing"],
    allergens: ["Milk"],
  },
  {
    id: "thracian-salad",
    name: "Thracian salad",
    nameBG: "Тракийска салата",
    weight: "350 g",
    price: 6.86,
    category: "salads",
    description: "Regional salad with the sun-ripe balance of the eastern fields.",
    ingredients: ["Seasonal vegetables", "Sirene", "Oil", "Herbs"],
    allergens: ["Milk"],
  },
  {
    id: "wallachian-salad",
    name: "Wallachian salad",
    nameBG: "Влашка салата",
    weight: "350 g",
    price: 7.45,
    category: "salads",
    description: "Hearty Balkan salad rooted in transhumance kitchens.",
    ingredients: ["Vegetables", "Cured notes", "Sirene", "Oil"],
    allergens: ["Milk"],
  },
  {
    id: "arugula-cherry-tomato",
    name: "Arugula & cherry tomato salad",
    nameBG: "Рукола с чери домати",
    weight: "320 g",
    price: 10.96,
    category: "salads",
    description: "Peppery leaves and sweet tomatoes — light and maritime.",
    ingredients: ["Arugula", "Cherry tomatoes", "Dressing", "Cheese or nuts"],
    allergens: ["Milk", "Tree nuts"],
  },
  {
    id: "greek-salad",
    name: "Greek salad",
    nameBG: "Гръцка салата",
    weight: "380 g",
    price: 8.03,
    category: "salads",
    description: "Feta, olives, ripe tomato — Aegean clarity without excess.",
    ingredients: ["Tomatoes", "Cucumbers", "Feta", "Olives", "Olive oil", "Oregano"],
    allergens: ["Milk"],
  },
  {
    id: "pink-tomato-mozzarella",
    name: "Pink tomato with mozzarella",
    nameBG: "Розов домат с моцарела",
    weight: "320 g",
    price: 9.81,
    category: "salads",
    description: "Heritage tomato and milky mozzarella in simple harmony.",
    ingredients: ["Pink tomato", "Mozzarella", "Basil", "Olive oil"],
    allergens: ["Milk"],
  },
  {
    id: "cherry-tomato-eggplant",
    name: "Cherry tomato with aubergine",
    nameBG: "Чери домат с патладжан",
    weight: "320 g",
    price: 10.39,
    category: "salads",
    description: "Smoky-soft eggplant with bright cherry tomatoes.",
    ingredients: ["Cherry tomatoes", "Aubergine", "Herbs", "Oil"],
  },
  {
    id: "green-salad",
    name: "Green salad",
    nameBG: "Зелена салата",
    weight: "300 g",
    price: 5.96,
    category: "salads",
    description: "Leaf-forward and clean — a composed palate reset.",
    ingredients: ["Mixed leaves", "Cucumber", "Dressing"],
  },
  {
    id: "caesar-chicken-bacon",
    name: "Caesar with chicken & bacon chips",
    nameBG: "Цезар с пиле и чипс от бекон",
    weight: "380 g",
    price: 11.56,
    category: "salads",
    description: "Familiar Caesar rhythm with grilled chicken and bacon crunch.",
    ingredients: ["Lettuce", "Chicken", "Bacon chips", "Dressing", "Cheese"],
    allergens: ["Milk", "Eggs", "Fish"],
  },
  {
    id: "monastery-layered-salad",
    name: "Monastery layered salad",
    nameBG: "Манастирска редена салата",
    weight: "380 g",
    price: 9.81,
    category: "salads",
    description: "Stacked layers — the house’s composed ‘monastery’ salad.",
    ingredients: ["Seasonal vegetables", "Sirene", "Dressing", "Herbs"],
    allergens: ["Milk"],
    isPopular: true,
  },
  {
    id: "tarama",
    name: "Taramasalata",
    nameBG: "Тарама хайвер",
    weight: "150 g",
    price: 6.28,
    category: "mezze",
    description: "Creamy fish-roe spread for bread or meze pacing.",
    ingredients: ["Fish roe", "Bread crumbs", "Oil", "Lemon"],
    allergens: ["Fish", "Gluten"],
  },
  {
    id: "fried-cheese-blueberry",
    name: "Fried melting cheese with blueberry jam",
    nameBG: "Панирани топени сиренца със сладко от боровинки",
    weight: "200 g",
    price: 8.96,
    category: "appetizers",
    description: "Crisp crust, melting heart, a ribbon of blueberry.",
    ingredients: ["Processed cheese", "Breadcrumbs", "Blueberry jam"],
    allergens: ["Milk", "Gluten", "Eggs"],
    isPopular: true,
  },
  {
    id: "crispy-chicken-fillets",
    name: "Crispy chicken fillets",
    nameBG: "Хрупкави пилешки филенца",
    weight: "280 g",
    price: 8.96,
    category: "appetizers",
    description: "Golden fillets — crisp shell, tender centre.",
    ingredients: ["Chicken breast", "Breading", "Dipping sauce"],
    allergens: ["Gluten", "Eggs"],
  },
  {
    id: "beef-tongue-butter",
    name: "Beef tongue in butter",
    nameBG: "Телешки език в масло",
    weight: "200 g",
    price: 10.45,
    category: "appetizers",
    description: "Slow work and gentle butter — classic mehana craft.",
    ingredients: ["Beef tongue", "Butter", "Garlic", "Parsley"],
    allergens: ["Milk"],
  },
  {
    id: "beef-tongue-fried",
    name: "Breaded beef tongue",
    nameBG: "Телешки език пане",
    weight: "200 g",
    price: 11.45,
    category: "appetizers",
    description: "Golden crumb, delicate meat — a composed starter.",
    ingredients: ["Beef tongue", "Breadcrumbs", "Pan oil"],
    allergens: ["Gluten", "Eggs"],
  },
  {
    id: "fried-kashkaval-katuk",
    name: "Fried kashkaval with tomatoes & katuk",
    nameBG: "Кашкавал пане с домати и катък",
    weight: "220 g",
    price: 11.57,
    category: "appetizers",
    description: "Crisp cheese with tomatoes and tangy katuk relish.",
    ingredients: ["Kashkaval", "Tomatoes", "Katuk", "Breading"],
    allergens: ["Milk", "Gluten", "Eggs"],
  },
  {
    id: "sirene-shopski",
    name: "Sirene po shopski (baked)",
    nameBG: "Сирене по шопски",
    weight: "200 g",
    price: 6.96,
    category: "appetizers",
    description: "Baked sirene with tomatoes and peppers — blistered and warm.",
    ingredients: ["Sirene", "Tomatoes", "Peppers", "Egg optional"],
    allergens: ["Milk", "Eggs"],
  },
  {
    id: "broccoli-four-cheeses",
    name: "Broccoli with four cheeses",
    nameBG: "Броколи с 4 вида сирена",
    weight: "300 g",
    price: 9.81,
    category: "appetizers",
    description: "Oven-melted cheeses over tender broccoli.",
    ingredients: ["Broccoli", "Cheese blend", "Cream"],
    allergens: ["Milk"],
  },
  {
    id: "grilled-vegetables-app",
    name: "Grilled vegetables",
    nameBG: "Гриловани зеленчуци",
    weight: "300 g",
    price: 6.35,
    category: "appetizers",
    description: "Ember-kissed seasonal vegetables, olive oil and sea salt.",
    ingredients: ["Zucchini", "Peppers", "Aubergine", "Oil"],
  },
  {
    id: "sauteed-potatoes",
    name: "Sautéed potatoes",
    nameBG: "Картофки соте",
    weight: "250 g",
    price: 5.69,
    category: "appetizers",
    description: "Buttery, herb-kissed potato coins.",
    ingredients: ["Potatoes", "Butter", "Herbs"],
    allergens: ["Milk"],
  },
  {
    id: "french-fries",
    name: "French fries",
    nameBG: "Пържени картофи",
    weight: "250 g",
    price: 5.11,
    category: "appetizers",
    description: "Clean oil, sea salt — honest and exact.",
    ingredients: ["Potatoes", "Oil", "Salt"],
  },
  {
    id: "french-fries-sirene",
    name: "French fries with sirene",
    nameBG: "Пържени картофи със сирене",
    weight: "280 g",
    price: 5.96,
    category: "appetizers",
    description: "Hot fries finished with crumbled sirene.",
    ingredients: ["Potatoes", "Sirene", "Oil"],
    allergens: ["Milk"],
  },
  {
    id: "scrambled-eggs-bruschetta",
    name: "Scrambled eggs with bruschetta",
    nameBG: "Бъркани яйца с брускета",
    weight: "220 g",
    price: 6.96,
    category: "appetizers",
    description: "Soft eggs on toasted bread with fresh tomato topping.",
    ingredients: ["Eggs", "Bread", "Tomatoes", "Butter"],
    allergens: ["Eggs", "Milk", "Gluten"],
  },
  {
    id: "vegan-risotto",
    name: "Vegan risotto",
    nameBG: "Веган ризото",
    weight: "350 g",
    price: 7.45,
    category: "risotto",
    description: "Plant-forward slow-stirred rice without dairy.",
    ingredients: ["Arborio rice", "Vegetable stock", "Seasonal veg"],
  },
  {
    id: "risotto-broccoli-porcini",
    name: "Risotto with broccoli & porcini",
    nameBG: "Ризото броколи и манатарки",
    weight: "380 g",
    price: 10.45,
    category: "risotto",
    description: "Forest mushrooms and broccoli folded through creamy rice.",
    ingredients: ["Rice", "Broccoli", "Porcini", "Parmesan style cheese"],
    allergens: ["Milk"],
  },
  {
    id: "risotto-chicken-zucchini",
    name: "Risotto with chicken & zucchini",
    nameBG: "Ризото пиле и тиквички",
    weight: "400 g",
    price: 10.45,
    category: "risotto",
    description: "Light zucchini ribbons with tender chicken bites.",
    ingredients: ["Rice", "Chicken", "Zucchini", "Stock"],
    allergens: ["Milk"],
  },
  {
    id: "chicken-pieces-pan-veg",
    name: "Chicken bites with vegetables, pan-fried",
    nameBG: "Пилешки хапки със зеленчуци на тиган",
    weight: "400 g",
    price: 10.45,
    category: "chicken",
    description: "Seared chicken with seasonal pan vegetables.",
    ingredients: ["Chicken", "Peppers", "Zucchini", "Oil"],
  },
  {
    id: "chicken-honey-garlic",
    name: "Chicken bites with honey & garlic",
    nameBG: "Пилешки хапки с мед и чесън",
    weight: "380 g",
    price: 9.85,
    category: "chicken",
    description: "Sticky-savoury glaze — harbour-evening comfort.",
    ingredients: ["Chicken", "Honey", "Garlic", "Soy-style glaze"],
  },
  {
    id: "chicken-bites-sauce-fries",
    name: "Chicken bites with light sauce & fries",
    nameBG: "Пилешки късчета с лек сос и фритирани картофи",
    weight: "420 g",
    price: 10.98,
    category: "chicken",
    description: "Crispy chicken with house sauce and chips.",
    ingredients: ["Chicken", "Fries", "Sauce"],
    allergens: ["Gluten"],
  },
  {
    id: "chicken-prosciutto",
    name: "Chicken with prosciutto",
    nameBG: "Пиле с прошуто",
    weight: "380 g",
    price: 15.44,
    category: "chicken",
    description: "Salt-cured ham wrapped richness over poultry.",
    ingredients: ["Chicken", "Prosciutto", "Wine sauce"],
  },
  {
    id: "chicken-spit",
    name: "Chicken on the spit",
    nameBG: "Пилешко вретено",
    weight: "450 g",
    price: 12.73,
    category: "chicken",
    description: "Rotisserie even colour, rosemary and smoke.",
    ingredients: ["Chicken", "Herbs", "Oil"],
  },
  {
    id: "chicken-drusan-kebab-parlenka",
    name: "Chicken drusan kebab on parlenka",
    nameBG: "Пилешки друсан кебап върху пърленка",
    weight: "420 g",
    price: 12.15,
    category: "chicken",
    description: "Spiced kebab ribbons over warm flatbread.",
    ingredients: ["Chicken", "Spices", "Flatbread"],
    allergens: ["Gluten"],
  },
  {
    id: "chicken-balkan-style",
    name: "Chicken Balkan style",
    nameBG: "Пиле по Балкански",
    weight: "420 g",
    price: 13.36,
    category: "chicken",
    description: "Pepper-tomato braise in the coastal mehana manner.",
    ingredients: ["Chicken", "Peppers", "Tomatoes", "Spices"],
  },
  {
    id: "chicken-julienne",
    name: "Chicken julienne",
    nameBG: "Пилешки жулиен",
    weight: "380 g",
    price: 11.57,
    category: "chicken",
    description: "Fine strips in cream-mushroom envelope.",
    ingredients: ["Chicken", "Mushrooms", "Cream"],
    allergens: ["Milk"],
  },
  {
    id: "chicken-steak-potatoes",
    name: "Chicken steak with roast potatoes",
    nameBG: "Пилешка пържола с печени картофки",
    weight: "450 g",
    price: 10.99,
    category: "chicken",
    description: "Seared chicken steak with oven potatoes.",
    ingredients: ["Chicken", "Potatoes", "Herbs"],
  },
  {
    id: "chicken-sword-monastery",
    name: "Chicken sabre ‘monastery style’",
    nameBG: "Пилешка сабя по манастирски",
    weight: "520 g",
    price: 16.86,
    category: "chicken",
    description: "Skewered showpiece for the table — smoke and savour.",
    ingredients: ["Chicken", "Vegetables", "Marinade"],
    isPopular: true,
  },
  {
    id: "pork-neck-steak-fried-veg",
    name: "Pork neck steak with fried vegetables",
    nameBG: "Свинска вратна пържола с фритирани зеленчуци",
    weight: "420 g",
    price: 11.57,
    category: "pork",
    description: "Marbled neck cut with crispy vegetable medley.",
    ingredients: ["Pork neck", "Vegetables", "Oil"],
  },
  {
    id: "wiener-schnitzel-fries",
    name: "Wiener schnitzel on fries",
    nameBG: "Виенски шницел върху пържени картофи",
    weight: "450 g",
    price: 12.45,
    category: "pork",
    description: "Golden schnitzel over hot chips — Viennese discipline.",
    ingredients: ["Pork", "Breadcrumbs", "Fries", "Lemon"],
    allergens: ["Gluten", "Eggs"],
  },
  {
    id: "trio-meatballs-saute-potatoes",
    name: "Trio of meatballs with sauté potatoes",
    nameBG: "Тройка кюфтета с картофки соте",
    weight: "400 g",
    price: 9.85,
    category: "pork",
    description: "Three spiced kufte with buttery potatoes.",
    ingredients: ["Minced pork", "Potatoes", "Spices"],
  },
  {
    id: "trio-kebapche-fries-lyutenitsa",
    name: "Trio kebapche with fries & lyutenitsa",
    nameBG: "Тройка кебапчета с пържени картофи и лютеница",
    weight: "420 g",
    price: 10.45,
    category: "pork",
    description: "Smoked paprika sausages, chips, and pepper relish.",
    ingredients: ["Kebapche", "Fries", "Lyutenitsa"],
  },
  {
    id: "mixed-grill-monastery",
    name: "Mixed grill ‘monastery style’",
    nameBG: "Мешана скара по манастирски",
    weight: "550 g",
    price: 16.35,
    category: "pork",
    description: "The grill as discipline: cuts and spice in one platter.",
    ingredients: ["Pork", "Chicken", "Kebapche", "Kufte", "Peppers"],
    isPopular: true,
  },
  {
    id: "bbq-ribs",
    name: "BBQ ribs with roast vegetables & ketchup",
    nameBG: "BBQ ребърца с печени зеленчуци и кетчуп",
    weight: "480 g",
    price: 13.45,
    category: "pork",
    description: "Smoke-ring ribs with glazed ketchup finish.",
    ingredients: ["Pork ribs", "Vegetables", "BBQ ketchup"],
  },
  {
    id: "pork-knuckle-mash",
    name: "Pork knuckle with mash & mushroom sauce",
    nameBG: "Свински джолан с картофено пюре и гъбен сос",
    weight: "550 g",
    price: 12.15,
    category: "pork",
    description: "Slow knuckle, silken mash, forest mushroom jus.",
    ingredients: ["Pork knuckle", "Potatoes", "Mushrooms"],
    allergens: ["Milk"],
  },
  {
    id: "homemade-sausage-veg",
    name: "Homemade sausage with roast vegetables",
    nameBG: "Домашна наденица с печени зеленчуци",
    weight: "420 g",
    price: 10.45,
    category: "pork",
    description: "House charcuterie with oven vegetables.",
    ingredients: ["Pork sausage", "Peppers", "Zucchini"],
  },
  {
    id: "pork-fillet-spit",
    name: "Pork fillet on the spit",
    nameBG: "Свинско филе вретено",
    weight: "450 g",
    price: 15.1,
    category: "pork",
    description: "Lean fillet, even colour from the rotisserie.",
    ingredients: ["Pork fillet", "Marinade", "Herbs"],
  },
  {
    id: "pork-vegetable-sword",
    name: "Pork & vegetable sabre",
    nameBG: "Сабя от свинско месо и зеленчуци",
    weight: "600 g",
    price: 18.03,
    category: "pork",
    description: "Marinated loin and vegetables on the skewer.",
    ingredients: ["Pork loin", "Peppers", "Onion", "Tomatoes"],
  },
  {
    id: "pork-chicken-sword",
    name: "Pork & chicken sabre with vegetables",
    nameBG: "Сабя от свинско и пилешко месо със зеленчуци",
    weight: "650 g",
    price: 20.95,
    category: "pork",
    description: "Two meats, one arc of smoke — composed for sharing.",
    ingredients: ["Pork", "Chicken", "Seasonal vegetables"],
  },
  {
    id: "rhodope-sach",
    name: "Rhodope sizzling plate (mixed)",
    nameBG: "Родопски сач със свинско, пилешко, наденичка и зеленчуци",
    weight: "700 g",
    price: 22.75,
    category: "pork",
    description: "Sach platter: pork, chicken, sausage and vegetables.",
    ingredients: ["Pork", "Chicken", "Sausage", "Peppers", "Onion"],
  },
  {
    id: "beef-knuckle-mash",
    name: "Beef knuckle with mash, roast sauce & basil",
    nameBG: "Телешки джолан с картофено пюре, печен сос и босилек",
    weight: "520 g",
    price: 13.91,
    category: "beefLamb",
    description: "Long-cooked beef with potato purée and herbed jus.",
    ingredients: ["Beef knuckle", "Potatoes", "Basil jus"],
    allergens: ["Milk"],
  },
  {
    id: "beef-meatballs-potatoes",
    name: "Beef meatballs with roast potatoes",
    nameBG: "Телешки кюфтенца с печени картофки",
    weight: "450 g",
    price: 12.15,
    category: "beefLamb",
    description: "Hand-rolled beef balls with crisp potatoes.",
    ingredients: ["Beef mince", "Potatoes", "Herbs"],
  },
  {
    id: "lamb-meatballs-potatoes",
    name: "Lamb meatballs with roast potatoes & sauce",
    nameBG: "Агнешки кюфтенца с печени картофки и сос",
    weight: "450 g",
    price: 12.15,
    category: "beefLamb",
    description: "Spring lamb notes with rosemary-leaning sauce.",
    ingredients: ["Lamb mince", "Potatoes", "Pan sauce"],
    allergens: ["Milk"],
  },
  {
    id: "lamb-shoulder-bone",
    name: "Roast lamb shoulder on the bone with potatoes & sauce",
    nameBG: "Агнешко печен врат с кост с печени картофки и сос",
    weight: "550 g",
    price: 22.15,
    category: "beefLamb",
    description: "Bone-in shoulder — slow colour, deep jus.",
    ingredients: ["Lamb shoulder", "Potatoes", "Sauce"],
    allergens: ["Milk"],
  },
  {
    id: "fried-turbot",
    name: "Fried turbot",
    nameBG: "Калкан пържен",
    weight: "400 g",
    price: 23.92,
    category: "seafood",
    description: "Whole or fillet turbot — crisp skin, sweet flesh.",
    ingredients: ["Turbot", "Lemon", "Oil"],
    allergens: ["Fish"],
  },
  {
    id: "vatos",
    name: "Vatos (daily fish)",
    nameBG: "Ватос",
    weight: "320 g",
    price: 15.03,
    category: "seafood",
    description: "Local catch treated simply — lemon and salt air.",
    ingredients: ["White fish", "Lemon", "Oil"],
    allergens: ["Fish"],
  },
  {
    id: "sardelle",
    name: "Sardelle (anchovy)",
    nameBG: "Сардела (хамсия)",
    weight: "200 g",
    price: 7.45,
    category: "seafood",
    description: "Small fish, big maritime flavour.",
    ingredients: ["Anchovy", "Flour", "Oil"],
    allergens: ["Fish", "Gluten"],
  },
  {
    id: "fried-safrid",
    name: "Fried saffron fish",
    nameBG: "Сафрид пържен",
    weight: "280 g",
    price: 8.62,
    category: "seafood",
    description: "Golden fried Black Sea saffron fish.",
    ingredients: ["Saffron fish", "Oil", "Lemon"],
    allergens: ["Fish"],
  },
  {
    id: "barbun",
    name: "Red mullet",
    nameBG: "Барбун",
    weight: "280 g",
    price: 8.62,
    category: "seafood",
    description: "Delicate red mullet from the morning boats.",
    ingredients: ["Red mullet", "Lemon", "Herbs"],
    allergens: ["Fish"],
  },
  {
    id: "grilled-bluefish",
    name: "Grilled bluefish",
    nameBG: "Чернокоп на скара",
    weight: "320 g",
    price: 13.45,
    category: "seafood",
    description: "Bluefish from the grill — oily and aromatic.",
    ingredients: ["Bluefish", "Oil", "Lemon"],
    allergens: ["Fish"],
  },
  {
    id: "grilled-garfish",
    name: "Grilled garfish",
    nameBG: "Зарган на скара",
    weight: "280 g",
    price: 10.85,
    category: "seafood",
    description: "Long silver fish — clean smoke line.",
    ingredients: ["Garfish", "Lemon", "Oil"],
    allergens: ["Fish"],
  },
  {
    id: "trout",
    name: "Trout",
    nameBG: "Пъстърва",
    weight: "320 g",
    price: 12.15,
    category: "seafood",
    description: "River trout — crisp skin, coral flesh.",
    ingredients: ["Trout", "Lemon", "Butter"],
    allergens: ["Fish", "Milk"],
  },
  {
    id: "sea-bream",
    name: "Sea bream",
    nameBG: "Ципура",
    weight: "400 g",
    price: 16.86,
    category: "seafood",
    description: "Whole or filleted tsipoura — silver and refined.",
    ingredients: ["Sea bream", "Lemon", "Herbs"],
    allergens: ["Fish"],
  },
  {
    id: "sea-bass",
    name: "Sea bass",
    nameBG: "Лаврак",
    weight: "400 g",
    price: 16.86,
    category: "seafood",
    description: "Lavrak on the plate — marina evening classic.",
    ingredients: ["Sea bass", "Olive oil", "Herbs"],
    allergens: ["Fish"],
  },
  {
    id: "lefer",
    name: "Lefer (large flatfish)",
    nameBG: "Лефер",
    weight: "450 g",
    price: 20.45,
    category: "seafood",
    description: "Premium flatfish — tender flakes.",
    ingredients: ["Lefer", "Lemon", "Oil"],
    allergens: ["Fish"],
  },
  {
    id: "tiger-prawns",
    name: "Tiger prawns",
    nameBG: "Тигрови скариди",
    weight: "320 g",
    price: 22.51,
    category: "seafood",
    description: "Charred shells, sweet tail meat — a guest favourite.",
    ingredients: ["Tiger prawns", "Garlic", "Butter"],
    allergens: ["Shellfish", "Milk"],
    isPopular: true,
  },
  {
    id: "spicy-shrimp",
    name: "Spicy shrimp",
    nameBG: "Скариди пикант",
    weight: "280 g",
    price: 15.1,
    category: "seafood",
    description: "Chilli-kissed shrimp with coastal heat.",
    ingredients: ["Shrimp", "Chilli", "Tomato"],
    allergens: ["Shellfish"],
  },
  {
    id: "calamari-greek",
    name: "Calamari Greek style",
    nameBG: "Калмари по гръцки",
    weight: "300 g",
    price: 14.05,
    category: "seafood",
    description: "Herb-lemon calamari — taverna clarity.",
    ingredients: ["Calamari", "Lemon", "Herbs", "Oil"],
    allergens: ["Molluscs"],
  },
  {
    id: "calamari-spicy",
    name: "Spicy calamari",
    nameBG: "Калмари пикант",
    weight: "280 g",
    price: 12.15,
    category: "seafood",
    description: "Chilli-glazed rings — crisp and bold.",
    ingredients: ["Calamari", "Spices", "Oil"],
    allergens: ["Molluscs", "Gluten"],
  },
  {
    id: "dessert-snickers",
    name: "Chocolate ‘Snickers’ dessert",
    nameBG: "Шоколадов десерт Сникърс",
    weight: "180 g",
    price: 9.45,
    category: "desserts",
    description: "Layered chocolate, caramel and nuts — indulgent close.",
    ingredients: ["Chocolate", "Caramel", "Nuts", "Biscuit"],
    allergens: ["Milk", "Eggs", "Gluten", "Tree nuts", "Peanuts"],
  },
  {
    id: "biscuit-cake",
    name: "Biscuit cake",
    nameBG: "Бисквитена торта",
    weight: "150 g",
    price: 6.91,
    category: "desserts",
    description: "No-bake layered biscuits and light cream.",
    ingredients: ["Biscuits", "Cream"],
    allergens: ["Milk", "Gluten"],
  },
  {
    id: "cherry-stone-dessert-unavailable",
    name: "‘Stone with cherries’ dessert (unavailable online)",
    nameBG: "Камъче с вишни — не е налично",
    weight: "—",
    price: 0.01,
    category: "desserts",
    description:
      "Listed on Takeaway as currently unavailable; price shown as placeholder on the platform.",
    ingredients: ["N/A"],
  },
  {
    id: "pizza-margherita",
    name: "Margherita",
    nameBG: "Маргарита",
    weight: "≈ 400 g",
    price: 7.99,
    category: "pizza",
    description: "Tomato, mozzarella, basil — restrained classic.",
    ingredients: ["Dough", "Tomato", "Mozzarella", "Basil"],
    allergens: ["Gluten", "Milk"],
    isPopular: true,
  },
  {
    id: "pizza-bianca",
    name: "White pizza",
    nameBG: "Бяла пица",
    weight: "≈ 420 g",
    price: 11.01,
    category: "pizza",
    description: "Cream-forward base without tomato.",
    ingredients: ["Dough", "Cream", "Cheese"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "pizza-running-chicken",
    name: "‘Running chicken’ pizza",
    nameBG: "Бягащо пиле",
    weight: "≈ 450 g",
    price: 11.01,
    category: "pizza",
    description: "House chicken-topped pizza with gentle spice.",
    ingredients: ["Dough", "Chicken", "Cheese", "Sauce"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "pizza-quattro-formaggi",
    name: "Four cheeses",
    nameBG: "Четири сирена",
    weight: "≈ 420 g",
    price: 12.15,
    category: "pizza",
    description: "Four-cheese melt — deep savour.",
    ingredients: ["Dough", "Cheese blend"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "pizza-pepperoni",
    name: "Pepperoni",
    nameBG: "Пеперони",
    weight: "≈ 430 g",
    price: 11.01,
    category: "pizza",
    description: "Cured sausage discs, blistered cheese.",
    ingredients: ["Dough", "Tomato", "Mozzarella", "Pepperoni"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "pizza-vegetariana",
    name: "Vegetariana",
    nameBG: "Вегетариана",
    weight: "≈ 450 g",
    price: 11.01,
    category: "pizza",
    description: "Seasonal vegetables over tomato and cheese.",
    ingredients: ["Dough", "Vegetables", "Mozzarella"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "pizza-chorbadjiyska",
    name: "Chorbadjiyska (loaded) pizza",
    nameBG: "Чорбаджийска",
    weight: "≈ 500 g",
    price: 15.99,
    category: "pizza",
    description: "Generous toppings — the house ‘rich man’ style pie.",
    ingredients: ["Dough", "Mixed meats", "Cheese", "Vegetables"],
    allergens: ["Gluten", "Milk"],
    isPopular: true,
  },
  {
    id: "parlenka-plain",
    name: "Parlenka (flatbread)",
    nameBG: "Пърленка",
    weight: "180 g",
    price: 4.35,
    category: "flatbread",
    description: "Coal-kissed flatbread — tear and share.",
    ingredients: ["Flour", "Oil", "Salt"],
    allergens: ["Gluten"],
  },
  {
    id: "parlenka-combo",
    name: "Combo parlenka",
    nameBG: "Комбинирана пърленка",
    weight: "220 g",
    price: 4.61,
    category: "flatbread",
    description: "Filled or topped combination flatbread.",
    ingredients: ["Flatbread", "Cheese", "Herbs"],
    allergens: ["Gluten", "Milk"],
  },
  {
    id: "coca-cola-330",
    name: "Coca-Cola 330 ml",
    nameBG: "Coca-Cola 330мл",
    weight: "330 ml",
    price: 2.1,
    category: "softDrinks",
    description: "Chilled classic cola.",
    ingredients: ["Carbonated soft drink"],
  },
  {
    id: "sparkling-water",
    name: "Sparkling water",
    nameBG: "Газирана вода",
    weight: "500 ml",
    price: 1.29,
    category: "softDrinks",
    description: "Cold sparkling mineral water.",
    ingredients: ["Water CO2"],
  },
  {
    id: "mineral-water",
    name: "Mineral still water (from)",
    nameBG: "Минерална вода (от)",
    weight: "500 ml",
    price: 1.3,
    category: "softDrinks",
    description: "Bottled mineral water — price as listed for the pour size.",
    ingredients: ["Mineral water"],
  },
  {
    id: "natural-juice",
    name: "Natural juice",
    nameBG: "Натурален сок",
    weight: "250 ml",
    price: 1.99,
    category: "softDrinks",
    description: "Fruit juice — server selects available flavour.",
    ingredients: ["Fruit juice"],
  },
  {
    id: "red-bull",
    name: "Red Bull",
    nameBG: "Ред бул",
    weight: "250 ml",
    price: 3.1,
    category: "softDrinks",
    description: "Energy drink, served chilled.",
    ingredients: ["Energy drink"],
    allergens: ["Caffeine"],
  },
  {
    id: "coffee",
    name: "Coffee",
    nameBG: "Кафе",
    weight: "40 ml",
    price: 1.99,
    category: "hotDrinks",
    description: "Espresso-style coffee.",
    ingredients: ["Coffee", "Water"],
  },
  {
    id: "nescafe",
    name: "Nescafé",
    nameBG: "Нес кафе",
    weight: "150 ml",
    price: 1.99,
    category: "hotDrinks",
    description: "Instant coffee — quick harbour warmth.",
    ingredients: ["Instant coffee", "Water", "Milk optional"],
    allergens: ["Milk"],
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    nameBG: "Капучино",
    weight: "180 ml",
    price: 2.99,
    category: "hotDrinks",
    description: "Espresso with foamed milk.",
    ingredients: ["Espresso", "Milk foam"],
    allergens: ["Milk"],
  },
  {
    id: "tea",
    name: "Tea",
    nameBG: "Чай",
    weight: "250 ml",
    price: 2.69,
    category: "hotDrinks",
    description: "Hot tea — black or herbal as available.",
    ingredients: ["Tea", "Water"],
  },
  {
    id: "beer-burgasko-can",
    name: "Burgasko (can)",
    nameBG: "Бургаско — кен",
    weight: "500 ml",
    price: 1.78,
    category: "beer",
    description: "Pale lager — 4.2% vol., 0.5 L can (18+).",
    ingredients: ["Water", "Malt", "Hops", "Yeast"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-staropramen-can",
    name: "Staropramen (can)",
    nameBG: "Старопрамен — кен",
    weight: "500 ml",
    price: 2.04,
    category: "beer",
    description: "Czech-style lager — 5% vol., 0.5 L can (18+).",
    ingredients: ["Water", "Malt", "Hops", "Yeast"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-kamenitsa",
    name: "Kamenitza",
    nameBG: "Каменица",
    weight: "500 ml",
    price: 2.13,
    category: "beer",
    description: "Bulgarian lager — easy seaside pour.",
    ingredients: ["Water", "Malt", "Hops"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-stella-artois",
    name: "Stella Artois",
    nameBG: "Стела артоа",
    weight: "500 ml",
    price: 2.91,
    category: "beer",
    description: "European lager — crisp finish.",
    ingredients: ["Water", "Malt", "Hops"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-corona",
    name: "Corona",
    nameBG: "Корона",
    weight: "330 ml",
    price: 3.52,
    category: "beer",
    description: "Pale lager with lime optional — beach-adjacent ritual.",
    ingredients: ["Water", "Malt", "Hops"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-heineken",
    name: "Heineken (as listed — small bottle)",
    nameBG: "Хайнекен",
    weight: "330 ml",
    price: 2.8,
    category: "beer",
    description: "As on takeaway listing (alcohol note varies by SKU — 18+).",
    ingredients: ["Water", "Malt", "Hops"],
    allergens: ["Gluten"],
  },
  {
    id: "beer-alcohol-free",
    name: "Alcohol-free beer",
    nameBG: "Безалкохолна бира",
    weight: "330 ml",
    price: 2.83,
    category: "beer",
    description: "Non-alcoholic lager-style beer.",
    ingredients: ["Water", "Malt", "Hops"],
    allergens: ["Gluten"],
  },
];
